//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProj.Framework.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGanr
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
