//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProj.Framework.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FilmGanr { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Otsenka { get; set; }
        public byte[] Photo { get; internal set; }
    }
}
