//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cats
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public string ID { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string CatTypeID { get; set; }
        public System.DateTime Birthday { get; set; }
        public string AddedBy { get; set; }
    
        public virtual CatType CatType { get; set; }
        public virtual User User { get; set; }
    }
}
