//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemeWpfApp.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meme
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DatePublishing { get; set; }
        public byte[] Image { get; set; }
        public int MemeTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual MemeType MemeType { get; set; }
        public virtual User User { get; set; }
    }
}
