//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProjectDB.DataBaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public int Language_Id { get; set; }
        public int LanguageType_Id { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public byte[] Image { get; set; }
    
        public virtual LanguageType LanguageType { get; set; }
    }
}
