//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoCraze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Melody
    {
        public int Id_Melody { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public byte[] Image { get; set; }
        public string Album { get; set; }
        public byte[] Audio { get; set; }
        public int Id_Genre { get; set; }
        public Nullable<int> Id_SortType { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Most_listened_to { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual SortType SortType { get; set; }
        public virtual User User { get; set; }
    }
}
