//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoCraze
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicdbEntities : DbContext
    {
        public MusicdbEntities()
            : base("name=MusicdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Melody> Melody { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SortType> SortType { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
