//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameWpfApp.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DataPublishing { get; set; }
        public byte[] Image { get; set; }
        public int GameTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual GameType GameType { get; set; }
        public virtual User User { get; set; }
    }
}
